[package]
name = "kobold"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
edition = "2021"

[dependencies]
kobold-wad = { path = "../kobold-wad" }

anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator = "0.5"
